### ISSUE TITLE
changing time resolution problem in preprocessing (i assume)

### ISSUE THREAD

**Issue by MartinKahn** [paulbrodersen/somnotate#4] opened 2021-05-05 20:06 UTC
When changing the below line to "time_resolution =4" in the config, then step two (test) returns a signal length mismatch error :

I think this is because in the preprocessing file the time resolution is hard coded? 

# desired time resolution of the automated annotation (in seconds)
time_resolution = 1

EDIT: I think the issue may be in this function here: 
convert_state_vector_to_state_intervals(state_vector, time_resolution=1., mapping=None):

**Comment by paulbrodersen** [comment] 2021-05-06 08:32
Hi Martin, thanks for raising the issue. I will look into it this afternoon.

**Comment by paulbrodersen** [comment] 2021-05-06 13:54
Just to make sure: you did re-run the preprocessing after changing the configuration and before attempting to test?

**Comment by MartinKahn** [comment] 2021-05-06 13:59
Yes I did - actually just got it to work when cjhanging this to 4 as well: 

convert_state_vector_to_state_intervals(state_vector, time_resolution=1., mapping=None):

This function is in under the hood of the code so I think it would be best to have it be changed automatically if the resolution is changed in the config?

**Comment by paulbrodersen** [comment] 2021-05-06 14:00
Yeah, I just reproduced the problem and it looks like I forgot to pass the time resolution in when loading the annotations. Should not be too difficult to fix.

**Comment by MartinKahn** [comment] 2021-05-06 14:17
OK awesome, thanks for the great work on this code!!!!

**Comment by paulbrodersen** [comment] 2021-05-06 14:24
Should be fixed by 4b3e8c6. I have tested scripts 01, 02, 03, 04, and 05 in the example pipeline and they seem to work now with a time_resolution other than 1. Can you pull the latest version, give it a spin, and report back if everything works now as expected?

**Comment by MartinKahn** [comment] 2021-05-06 14:26
ok will do! Thanks again!

**Comment by paulbrodersen** [comment] 2021-05-17 13:21
Since I haven't heard from you in a while, I am assuming that the issue is resolved. However, feel free to re-open if that is not the case.

**Closed by paulbrodersen** 2021-05-17 13:21 UTC

**Comment by MartinKahn** [comment] 2021-05-18 21:40
I have stuck with the old version for now because it worked with our monkey patch but we'll soon install it on more PCs and let you know. Thanks for your work!

**Comment by MartinKahn** [comment] 2021-05-25 17:55
Hi Paul, I just checked and the piece of code that I had to change to get the time resolution to work still seems unchanged. I'm aware there is a very high chance that your fix already takes care of this but just wanted to confirm: 

in "utils.py", the following function: 

convert_state_vector_to_state_intervals(state_vector, time_resolution=1, mapping=None):

The time resolution is hardcoded to =1, and when I change it to =4 then things work.

**Comment by paulbrodersen** [comment] 2021-05-26 13:13
I probably left it at the default 1 second time resolution as that seems a more sensible default. However, the time resolution parameter specified in the configuration.py file should now be passed through to all the relevant places. Have you actually tried the new version yet?
