### ISSUE TITLE
Using different vigilance states

### ISSUE THREAD

**Issue by rjp109** [paulbrodersen/somnotate#13] opened 2024-08-16 10:20 UTC
I have 4 vigilance states i want to score - wake, nrem, rem and artefact (any stage). I have modified these in the configuration file but i am getting the following error when running '02_test_state_annotation.py' .

`Loading data sets... C:\Users\rp17047\22qScore\processed\148139_301123.npy (1/2) C:\Users\rp17047\somnotate\somnotate\_utils.py:145: UserWarning: Interval values are converted from floats to integers. warnings.warn("Interval values are converted from floats to integers.") C:\Users\rp17047\22qScore\processed\148140_301123.npy (2/2) Testing... C:\Users\rp17047\22qScore\processed\148139_301123.npy (1/2) accuracy : 91.5% Traceback (most recent call last): File "C:\Users\rp17047\somnotate\example_pipeline\02_test_state_annotation.py", line 114, in <module> confusion[ii] = get_confusion_matrix(np.abs(state_vectors[ii]), annotator.predict(signal_arrays[ii]), labels=unique_states) ValueError: could not broadcast input array from shape (3,3) into shape (4,4) (somnotate_env) C:\Users\rp17047\somnotate> (somnotate_env) C:\Users\rp17047\somnotate>python C:\Users\rp17047\somnotate\example_pipeline\02_test_state_annotation.py C:\Users\rp17047\22qScore\TrainingSetshort.csv Loading data sets... C:\Users\rp17047\22qScore\processed\148139_301123.npy (1/2) C:\Users\rp17047\somnotate\somnotate\_utils.py:145: UserWarning: Interval values are converted from floats to integers. warnings.warn("Interval values are converted from floats to integers.") C:\Users\rp17047\22qScore\processed\148140_301123.npy (2/2) Testing... C:\Users\rp17047\22qScore\processed\148139_301123.npy (1/2) accuracy : 91.5% Traceback (most recent call last): File "C:\Users\rp17047\somnotate\example_pipeline\02_test_state_annotation.py", line 114, in <module> confusion[ii] = get_confusion_matrix(np.abs(state_vectors[ii]), annotator.predict(signal_arrays[ii]), labels=unique_states) ValueError: could not broadcast input array from shape (3,3) into shape (4,4)`

I have modified the configuration file as follows, i did try leaving in the unused variables, but it did not help

`state_to_int = dict([
    ('Wake'               ,  1),
    ('Art'                , -1),`
` #  ('sleep movement'     ,  1),`
`    ('N2'                 ,  2),`
`  #  ('non-REM (artefact)' , -2),`
`    ('REM'                ,  3),`
`  # ('REM (artefact)'     , -3),`
`    ('undefined'          ,  0), ])`

`# Construct the inverse mapping to convert back from state predictions to human readabe labels. int_to_state = {ii : state for state, ii in state_to_int.items() if state != 'sleep movement'}`

`# define the keymap used for the manual annotation`
`keymap = { 'w' : 'Wake', 'W' : 'Art', 'n' : 'N2',`
`   # 'N' : 'non-REM (artefact)',`
`    'r' : 'REM',`
`   # 'R' : 'REM (artefact)',`
`    'x' : 'undefined',`
` #   'X' : 'undefined (artefact)',`
`  #  'm' : 'sleep movement',`
` #   'M' : 'sleep movement (artefact)', }`

`# define the visual display of states`
`state_to_color = {`
`    'Wake'                : 'crimson',`
`    'Art'                 : 'coral',`
` #   'sleep movement'      : 'violet',`
 `   'N2'                  : 'blue',`
`   # 'non-REM (artefact)'  : 'cornflowerblue',`
 `   'REM'                 : 'gold',`
`    #'REM (artefact)'      : 'yellow',`
` #   'sleep movement'      : 'purple',`
 `   'undefined'           : 'gray',`
 ` #  'undefined (artefact)': 'lightgray',`
`}`

`state_display_order = [ 'Wake',`
` 'Art',`
` 'N2',`
 `  # 'non-REM (artefact)',`
`    'REM',`
`   # 'REM (artefact)',`
`  #  'sleep movement',`
`  #  'sleep movement (artefact)',`
`    'undefined',`
 ` #  'undefined (artefact)',`
`]`

**Comment by paulbrodersen** [comment] 2024-08-16 11:15
Two comments on this issue: 

1. This is a bug that seems to occur because one of the states is completely absent from one of the recordings. While the code could be changed to accommodate this scenario, it strongly suggests that your data cannot be modeled well by a Markov chain process. 

2. The core idea of Markov models is that there are distinct processes ("states") that generate your data ("emissions") and the system occasionally switches between the processes. A core requirement is that within a process, the distribution of the data is stationary, i.e. the distribution of values generated during the first time that state is visited is indistinguishable from the distribution of values the next time that state is visited. A catch-all artefact state is unlikely to be stationary. The artefacts during wakefullness will be very different from artefacts during NREM, and even within wakefulness, artefact states will differ substantially.  The wake/artefact/NREM/REM parcellation is hence unlikely to work well. 

The pipeline is very robust to artefacts (that is the whole point of the hidden Markov model). The typical workflow is hence to annotate the data with all three vigilance states first and then clean the data in a second step. High state likelihoods (>99.9%) can be used to determine subsets of the data that are likely artefact free, but will result in many false positives, particularly around state transitions (where the states are often mixed resulting in intermediate likelihood values even in the absence of artefacts). Otherwise, you will have need to annotate the artefacts manually -- at least none of the artefact detection software solutions I have tried were any good.

**Comment by rjp109** [comment] 2024-08-16 11:43
Thank you for the explanation. Would it therefore work okay to just use Wake, NREM and REM only, and manually rescoring my artefacts to one of those states?
When you say the typical workflow is to clean the data in a second step - is this after running somnotate and basically ignoring low state likelihoods? Or do you mean actually removing artefact epochs from the data beforehand?

**Comment by paulbrodersen** [comment] 2024-08-16 12:43
> When you say the typical workflow is to clean the data in a second step - is this after running somnotate and basically ignoring low state likelihoods? 

Correct. The state inference should be quite robust to even large artefacts, such that their existence can be ignored during the state inference. Then in a second step you remove artefacts manually, or you use the state likelihood to identify a subset of the data that is likely pretty clean.

**Comment by rjp109** [comment] 2024-08-16 13:56
Ah amazing, thanks, I can give that a go.

**Comment by rjp109** [comment] 2024-08-20 10:32
Hello, I have edited my manual hypnograms to only inlcude awake, non-REM, REM. They all contain all of these states. I have also tried using the same original configuration file as used with the example data - some of those example hypnograms also only include 3 states so my data should be identical in format. However, i am still getting the same error as before. Is this perhaps becuse my recordings are too short? Typically I'm only recording for ~3hours. Is there any way around this?

**Comment by paulbrodersen** [comment] 2024-08-20 10:53
I may have found the problem, but I will need to think carefully how I fix it without breaking the pipeline for other people. 
Basically, the pre-allocation of the confusion matrix assumes that there are always some `"undefined"` samples in the manual annotation, and that these are mapped to `0`. This is not ideal. 

In the meantime, the simplest fix for you would be to set any entry (e.g. the first and/or last) in each of your manual annotations to zero.

**Comment by rjp109** [comment] 2024-08-20 10:59
Hmm ok i will try, but the consensus_state_annotation hypnogram for SampleFile_B also has no "undefined" samples? And it works fine.

**Comment by rjp109** [comment] 2024-08-20 11:16
Update: I added just one "undefined" at the end of my first hypnogram and now it is working (despite none of the other hypnograms having an "undefined")

**Comment by paulbrodersen** [comment] 2024-08-20 11:57
Yeah, you are right. Upon reading the code again, a single `undefined` anywhere should be sufficient for the current pipeline to work as intended. This issue will be fixed, just not today.

**Comment by rjp109** [comment] 2024-08-20 14:48
Okay thank you! Seems to work well enough for now :)

**Comment by paulbrodersen** [comment] 2024-08-23 11:28
This issue should be fixed in the latest version. Thanks for reporting!

**Closed by paulbrodersen** 2024-08-23 11:28 UTC
